In [209]:
#import all neccessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [210]:
#read the energy dataset
energy_df = pd.read_csv("energy_Data.csv")
energy_df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [211]:
#display columns
energy_df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [212]:
#drop the lights and date columns
energy_data = energy_df.drop(["date","lights"],axis =1)
energy_data.head()

Appliances     T1       RH_1    T2       RH_2     T3       RH_3         T4  \
0          60  19.89  47.596667  19.2  44.790000  19.79  44.730000  19.000000   
1          60  19.89  46.693333  19.2  44.722500  19.79  44.790000  19.000000   
2          50  19.89  46.300000  19.2  44.626667  19.79  44.933333  18.926667   
3          50  19.89  46.066667  19.2  44.590000  19.79  45.000000  18.890000   
4          60  19.89  46.333333  19.2  44.530000  19.79  45.000000  18.890000   

        RH_4         T5  ...         T9   RH_9     T_out  Press_mm_hg  RH_out  \
0  45.566667  17.166667  ...  17.033333  45.53  6.600000        733.5    92.0   
1  45.992500  17.166667  ...  17.066667  45.56  6.483333        733.6    92.0   
2  45.890000  17.166667  ...  17.000000  45.50  6.366667        733.7    92.0   
3  45.723333  17.166667  ...  17.000000  45.40  6.250000        733.8    92.0   
4  45.530000  17.200000  ...  17.000000  45.40  6.133333        733.9    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv2  
0   7.000000   63.000000        5.3  13.275433  13.275433  
1   6.666667   59.166667        5.2  18.606195  18.606195  
2   6.333333   55.333333        5.1  28.642668  28.642668  
3   6.000000   51.500000        5.0  45.410389  45.410389  
4   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 27 columns]

In [213]:
#displays the info of the dataframe
energy_data.info()
#there are no missing values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 27 columns):
Appliances     19735 non-null int64
T1             19735 non-null float64
RH_1           19735 non-null float64
T2             19735 non-null float64
RH_2           19735 non-null float64
T3             19735 non-null float64
RH_3           19735 non-null float64
T4             19735 non-null float64
RH_4           19735 non-null float64
T5             19735 non-null float64
RH_5           19735 non-null float64
T6             19735 non-null float64
RH_6           19735 non-null float64
T7             19735 non-null float64
RH_7           19735 non-null float64
T8             19735 non-null float64
RH_8           19735 non-null float64
T9             19735 non-null float64
RH_9           19735 non-null float64
T_out          19735 non-null float64
Press_mm_hg    19735 non-null float64
RH_out         19735 non-null float64
Windspeed      19735 non-null float64
Visibility     1973

In [214]:
#the summary statistics
energy_data.describe()

Appliances            T1          RH_1            T2          RH_2  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      97.694958     21.686571     40.259739     20.341219     40.420420   
std      102.524891      1.606066      3.979299      2.192974      4.069813   
min       10.000000     16.790000     27.023333     16.100000     20.463333   
25%       50.000000     20.760000     37.333333     18.790000     37.900000   
50%       60.000000     21.600000     39.656667     20.000000     40.500000   
75%      100.000000     22.600000     43.066667     21.500000     43.260000   
max     1080.000000     26.260000     63.360000     29.856667     56.026667   

                 T3          RH_3            T4          RH_4            T5  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      22.267611     39.242500     20.855335     39.026904     19.592106   
std        2.006111      3.254576      2.042884      4.341321      1.844623   
min       17.200000     28.766667     15.100000     27.660000     15.330000   
25%       20.790000     36.900000     19.530000     35.530000     18.277500   
50%       22.100000     38.530000     20.666667     38.400000     19.390000   
75%       23.290000     41.760000     22.100000     42.156667     20.619643   
max       29.236000     50.163333     26.200000     51.090000     25.795000   

       ...            T9          RH_9         T_out   Press_mm_hg  \
count  ...  19735.000000  19735.000000  19735.000000  19735.000000   
mean   ...     19.485828     41.552401      7.411665    755.522602   
std    ...      2.014712      4.151497      5.317409      7.399441   
min    ...     14.890000     29.166667     -5.000000    729.300000   
25%    ...     18.000000     38.500000      3.666667    750.933333   
50%    ...     19.390000     40.900000      6.916667    756.100000   
75%    ...     20.600000     44.338095     10.408333    760.933333   
max    ...     24.500000     53.326667     26.100000    772.300000   

             RH_out     Windspeed    Visibility     Tdewpoint           rv1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      79.750418      4.039752     38.330834      3.760707     24.988033   
std       14.901088      2.451221     11.794719      4.194648     14.496634   
min       24.000000      0.000000      1.000000     -6.600000      0.005322   
25%       70.333333      2.000000     29.000000      0.900000     12.497889   
50%       83.666667      3.666667     40.000000      3.433333     24.897653   
75%       91.666667      5.500000     40.000000      6.566667     37.583769   
max      100.000000     14.000000     66.000000     15.500000     49.996530   

                rv2  
count  19735.000000  
mean      24.988033  
std       14.496634  
min        0.005322  
25%       12.497889  
50%       24.897653  
75%       37.583769  
max       49.996530  

[8 rows x 27 columns]

In [215]:
#normalise the dataset to a uniform scale using the min max scale
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()#instantiate the min max scaler
#then we fit,transform 
#and also convert to a dataframe since it comes as a numpy array
norm_data = pd.DataFrame(scaler.fit_transform(energy_data),columns=energy_data.columns)

In [216]:
norm_data.head()

Appliances       T1      RH_1        T2      RH_2        T3      RH_3  \
0    0.046729  0.32735  0.566187  0.225345  0.684038  0.215188  0.746066   
1    0.046729  0.32735  0.541326  0.225345  0.682140  0.215188  0.748871   
2    0.037383  0.32735  0.530502  0.225345  0.679445  0.215188  0.755569   
3    0.037383  0.32735  0.524080  0.225345  0.678414  0.215188  0.758685   
4    0.046729  0.32735  0.531419  0.225345  0.676727  0.215188  0.758685   

         T4      RH_4        T5  ...        T9      RH_9     T_out  \
0  0.351351  0.764262  0.175506  ...  0.223032  0.677290  0.372990   
1  0.351351  0.782437  0.175506  ...  0.226500  0.678532  0.369239   
2  0.344745  0.778062  0.175506  ...  0.219563  0.676049  0.365488   
3  0.341441  0.770949  0.175506  ...  0.219563  0.671909  0.361736   
4  0.341441  0.762697  0.178691  ...  0.219563  0.671909  0.357985   

   Press_mm_hg    RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0     0.097674  0.894737   0.500000    0.953846   0.538462  0.265449  0.265449  
1     0.100000  0.894737   0.476190    0.894872   0.533937  0.372083  0.372083  
2     0.102326  0.894737   0.452381    0.835897   0.529412  0.572848  0.572848  
3     0.104651  0.894737   0.428571    0.776923   0.524887  0.908261  0.908261  
4     0.106977  0.894737   0.404762    0.717949   0.520362  0.201611  0.201611  

[5 rows x 27 columns]

# Question 12
From the dataset, fit a linear model on the relationship between the temperature in the living room in Celsius (x = T2) and the temperature outside the building (y = T6). What is the R^2 value in two D.P

In [217]:
#select the features and pass them as numpy arrays
X = np.array(norm_data[["T2"]]) #the predictor
y = np.array(norm_data[["T6"]] )# the target

In [218]:
#split the data into train and test set
from sklearn.model_selection import train_test_split

In [219]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.3,random_state=42)

In [220]:
#fit the train sets
reg = LinearRegression()#instantiate the regression object
#fit the model to the train sets
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [221]:
#obtain predictions using the test sets
reg_prediction = reg.predict(X_test)

In [222]:
reg_prediction

array([[0.23928945],
       [0.46794238],
       [0.23108472],
       ...,
       [0.3001772 ],
       [0.4297256 ],
       [0.3217686 ]])

In [223]:
#to get the weight of the regression
reg_coefficient = reg.coef_ #returns an array

In [224]:
#we index 
reg_coefficient[0]

array([0.8910771])

In [225]:
#the intercept
reg.intercept_

array([0.13176428])

In [226]:
accuracy  = reg.score(X_test,y_test)
round(accuracy,2)

0.64

In [227]:
#generate the features data from the normalised dataset by dropping the target
X = norm_data.drop(["Appliances"],axis = 1)

In [228]:
#generate the target dataframe
y = norm_data["Appliances"]

In [229]:
#split the normalised data into train and test sets
X_train, X_test,y_train,y_test= train_test_split(X,y,test_size = 0.3,random_state = 42)

In [230]:
#the shape of each set
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(13814, 26)
(5921, 26)
(13814,)
(5921,)


In [231]:
#fit the train sets
reg = LinearRegression()#instantiate the regression object
#fit the model to the train sets
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [232]:
#obtain predictions using the test sets
reg_prediction = reg.predict(X_test)
reg_prediction

array([0.03322207, 0.24411599, 0.03400024, ..., 0.06844707, 0.10032325,
       0.05722198])

In [233]:
#import sklearn libraries
from sklearn.linear_model import Lasso, Ridge
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# Question 13

What is the Mean Absolute Error (in two decimal places)?


In [234]:
#calculating the MAE for linear regression
reg_mae = mean_absolute_error(y_test,reg_prediction)
round(reg_mae,2)

0.05

# Question 14
What is the Residual Sum of Squares (in two decimal places)?

In [235]:
#calculating rss
reg_rss = np.sum(np.square(y_test - reg_prediction))
round(reg_rss, 2)

45.35

# Question 15

What is the Root Mean Squared Error (in three decimal places)?


In [236]:
#calculating the root mean squared error for the linear regression
reg_rmse=np.sqrt(mean_squared_error(y_test,reg_prediction))
round(reg_rmse,3)

0.088

# Question 16

What is the Coefficient of Determination (in two decimal places)? 


In [237]:
#calculating the r square of the linear regression
reg_r2 = r2_score(y_test,reg_prediction)
round(reg_r2,2)

0.15

Question 17

Obtain the feature weights from your linear model above. Which features have the lowest and highest weights respectively?

**rh2 and rh1**

In [238]:
#comparing the effects of regularisation
def get_weights_df(model, feat, col_name):
    #this function returns the weight of every feature
    weights = pd.Series(model.coef_, feat.columns).sort_values()
    weights_df = pd.DataFrame(weights).reset_index()
    weights_df.columns = ['Features', col_name]
    weights_df[col_name].round(3)
    return weights_df
    #the higher the weight, the more important it is in predicting the values

In [239]:
linear_model_weights = get_weights_df(reg, X_train, 'Linear_Model_Weight')
linear_model_weights

Features  Linear_Model_Weight
0          RH_2            -0.456698
1         T_out            -0.321860
2            T2            -0.236178
3            T9            -0.189941
4          RH_8            -0.157595
5        RH_out            -0.077671
6          RH_7            -0.044614
7          RH_9            -0.039800
8            T5            -0.015657
9            T1            -0.003281
10          rv1             0.000770
11          rv2             0.000770
12  Press_mm_hg             0.006839
13           T7             0.010319
14   Visibility             0.012307
15         RH_5             0.016006
16         RH_4             0.026386
17           T4             0.028981
18    Windspeed             0.029183
19         RH_6             0.038049
20         RH_3             0.096048
21           T8             0.101995
22    Tdewpoint             0.117758
23           T6             0.236425
24           T3             0.290627
25         RH_1             0.553547

# Question 18

Train a ridge regression model with an alpha value of 0.4. Is there any change to the root mean squared error (RMSE) when evaluated on the test set?

**no change**

In [240]:
#use a ridge regression to train
ridge_reg = Ridge(alpha=0.4)
#fit ridge_reg
ridge_reg.fit(X_train,y_train)

Ridge(alpha=0.4, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [241]:
#use a ridge regression to predict
ridge_predict = ridge_reg.predict(X_test)
ridge_predict

array([0.03321872, 0.24043824, 0.03461337, ..., 0.06872351, 0.10025536,
       0.05851175])

In [242]:
#calculating the root mean square for the ridge regression
ridge_rmse = np.sqrt(mean_squared_error(y_test,ridge_predict))
round(ridge_rmse,3)

0.088

In [243]:
#calculating the root mean squared error for the linear regression
reg_rmse=np.sqrt(mean_squared_error(y_test,reg_prediction))
round(reg_rmse,3)

0.088

# Question 19
Train a lasso regression model with an alpha value of 0.001 and obtain the new feature weights with it. How many of the features have non-zero feature weights

**4**


In [244]:
#use a lasso regression 
lasso_reg = Lasso(alpha=0.001)
#fit lasso_reg
lasso_reg.fit(X_train,y_train)

Lasso(alpha=0.001, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [245]:
lasso_predict  = lasso_reg.predict(X_test)
lasso_predict

array([0.07370267, 0.08143458, 0.07716072, ..., 0.07792848, 0.09034412,
       0.08359255])

In [246]:
lasso_weights_df = get_weights_df(lasso_reg, X_train, 'Lasso_weight')
lasso_weights_df

Features  Lasso_weight
0        RH_out     -0.049557
1          RH_8     -0.000110
2            T1      0.000000
3     Tdewpoint      0.000000
4    Visibility      0.000000
5   Press_mm_hg     -0.000000
6         T_out      0.000000
7          RH_9     -0.000000
8            T9     -0.000000
9            T8      0.000000
10         RH_7     -0.000000
11          rv1     -0.000000
12           T7     -0.000000
13           T6      0.000000
14         RH_5      0.000000
15           T5     -0.000000
16         RH_4      0.000000
17           T4     -0.000000
18         RH_3      0.000000
19           T3      0.000000
20         RH_2     -0.000000
21           T2      0.000000
22         RH_6     -0.000000
23          rv2     -0.000000
24    Windspeed      0.002912
25         RH_1      0.017880

# Question 20

What is the new RMSE with the Lasso Regression (in 3 decimal places)?  


In [247]:
#calculate the root mean square for the lasso regression
lasso_rmse = np.sqrt(mean_squared_error(y_test,lasso_predict))
round(lasso_rmse,3)

0.094

In [248]:
#all weights merged together
final_weights = pd.merge(linear_model_weights, ridge_weights_df, on='Features')
final_weights = pd.merge(final_weights, lasso_weights_df, on='Features')
final_weights

Features  Linear_Model_Weight  Ridge_Weight  Lasso_weight
0          RH_2            -0.456698     -0.411071     -0.000000
1         T_out            -0.321860     -0.262172      0.000000
2            T2            -0.236178     -0.201397      0.000000
3            T9            -0.189941     -0.188916     -0.000000
4          RH_8            -0.157595     -0.156830     -0.000110
5        RH_out            -0.077671     -0.054724     -0.049557
6          RH_7            -0.044614     -0.045977     -0.000000
7          RH_9            -0.039800     -0.041367     -0.000000
8            T5            -0.015657     -0.019853     -0.000000
9            T1            -0.003281     -0.018406      0.000000
10          rv1             0.000770      0.000748     -0.000000
11          rv2             0.000770      0.000748     -0.000000
12  Press_mm_hg             0.006839      0.006584     -0.000000
13           T7             0.010319      0.010098     -0.000000
14   Visibility             0.012307      0.012076      0.000000
15         RH_5             0.016006      0.016152      0.000000
16         RH_4             0.026386      0.024579      0.000000
17           T4             0.028981      0.027384     -0.000000
18    Windspeed             0.029183      0.030268      0.002912
19         RH_6             0.038049      0.035519     -0.000000
20         RH_3             0.096048      0.095135      0.000000
21           T8             0.101995      0.101028      0.000000
22    Tdewpoint             0.117758      0.083128      0.000000
23           T6             0.236425      0.217292      0.000000
24           T3             0.290627      0.288087      0.000000
25         RH_1             0.553547      0.519525      0.017880